// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'


show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTD7MC3PEJa5bTPw0_MeNwOy4fHgbqDt4',
    appId: '1:1012526372803:web:66274f4d1eae86bf62cf76',
    messagingSenderId: '1012526372803',
    projectId: 'push-notificacions-test',
    authDomain: 'push-notificacions-test.firebaseapp.com',
    storageBucket: 'push-notificacions-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1XJtGv1x7YaDzw20YXAg9BToDRC-kClI',
    appId: '1:1012526372803:android:53adbdb4a987d9f062cf76',
    messagingSenderId: '1012526372803',
    projectId: 'push-notificacions-test',
    storageBucket: 'push-notificacions-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR43yt8zy7shlK29WsViaP2pcYHNu-aBE',
    appId: '1:1012526372803:ios:fb9c2d2408069c7762cf76',
    messagingSenderId: '1012526372803',
    projectId: 'push-notificacions-test',
    storageBucket: 'push-notificacions-test.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationsTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR43yt8zy7shlK29WsViaP2pcYHNu-aBE',
    appId: '1:1012526372803:ios:fb9c2d2408069c7762cf76',
    messagingSenderId: '1012526372803',
    projectId: 'push-notificacions-test',
    storageBucket: 'push-notificacions-test.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationsTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTD7MC3PEJa5bTPw0_MeNwOy4fHgbqDt4',
    appId: '1:1012526372803:web:c152e614b7d90ca262cf76',
    messagingSenderId: '1012526372803',
    projectId: 'push-notificacions-test',
    authDomain: 'push-notificacions-test.firebaseapp.com',
    storageBucket: 'push-notificacions-test.firebasestorage.app',
  );
}
